services:
  postgres-db:
    container_name: postgresDb
    image: postgres:16.0
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    networks:
      - shared

  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgres-db
    command:
      - --searchPath=/changesets
      - --changelog-file=db.changelog-master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres-db:5432/test
      - --username=test
      - --password=test
      - update
    volumes:
      - ./changelog:/changesets
    networks:
      - shared

volumes:
  postgres-data-test:
